### ISSUE TITLE
Calling a `sls webpack serve` endpoint throws "TypeError: func is not a function"

### ISSUE THREAD

**Issue by marcuswhybrow** [elastic-coders/serverless-webpack#46] opened 2016-10-11 23:06 UTC
`func` represents the handler function defined in `serverless.yml`.

It seems [this block](https://github.com/elastic-coders/serverless-webpack/blob/v1.0.0-rc.2/lib/serve.js#L77-L82) initially sets `handlerFunc` (later referred to as `func`) to `null`. Setting it to `funcConf.handler.split('.')[0]` fixes the issue.

However, it looks like we have [webpack setting the `handlerFunc`](https://github.com/elastic-coders/serverless-webpack/blob/v1.0.0-rc.2/lib/serve.js#L24-L28) later on. I'm not sure what `loadHandler` does, or why it's important.

I searched the webpack docs and source but couldn't find reference to a `loadHandler`.

**Comment by smkamranqadri** [comment] 2016-10-17 07:56
same issue with me!

**Comment by rivertam** [comment] 2016-10-20 16:13
`loadHandler` is in `lib/run`. I haven't been able to figure out exactly why it's resulting in `null` only some times.

**Comment by PerryBirch** [comment] 2016-10-23 21:26
Try setting output:
libraryTarget: 'commonjs2',

**Comment by rivertam** [comment] 2016-10-24 18:19
@PerryBirch changes nothing

**Comment by thenikso** [comment] 2016-11-17 11:18
the `loadHandler` is used to reload the function from disk to address hot reloading. There might be a problem with how hot reloading is implemented that does not produce a "func" but I'm not quite sure why. Has anyone had more luck in debugging this issue?

**Comment by rvaidya** [comment] 2016-11-17 21:12
I get this error only before the .webpack folder has been created - the console looks like it's ready and serving routes even though the webpack build is still happening in the background.

**Comment by briananderson1222** [comment] 2016-12-09 00:34
Is there any more news on this or steps to get around it?

**Comment by fersman** [comment] 2016-12-21 21:48
In my case the problem was that starting my function failed. And then I got this error. Try to add this to beggining of your handler (it will report errors):

process.on('uncaughtException', function (err) {
    console.log(err);
});

**Comment by thenikso** [comment] 2016-12-23 16:50
I was able to reproduce it last time but it seams fixed for me in the latest rc.3

Are you still expecting this issue?

**Comment by EQuimper** [comment] 2017-03-01 15:14
I got in in version rc.4

**Comment by rvaidya** [comment] 2017-03-01 17:30
As of my PR (https://github.com/elastic-coders/serverless-webpack/pull/58) using serverless-offline (https://github.com/dherault/serverless-offline) together with serverless-webpack should be the way to go for local testing

**Comment by HyperBrain** [comment] 2017-07-28 18:05
`serve` will be removed in the next `v3.0.0` release in favor of `serverless-offline` (see #152 ). No efforts will be spent on the function anymore. So I'll close this issue.

**Closed by HyperBrain** 2017-07-28 18:05 UTC
Labels: issue/serve
