### ISSUE TITLE
serverless deploy <=1.17 overwrites webpack packed version in v3.0.0-rc.2 and not in v2.2.2

### ISSUE THREAD

**Issue by l-hendriks** [elastic-coders/serverless-webpack#206] opened 2017-08-25 12:33 UTC
# This is a Bug Report

## Description

* What went wrong?

Running `serverless deploy` with serverless version 1.17 and serverless-webpack version 3.0.0-rc.2 does not work. The webpack packed version is overwritten by the unpacked zip file created by serverless.

* What did you expect should have happened?

When using serverless-webpack, the serverless should not create a zip file that overwrites the zip file created by serverless-webpack

## Additional Data

* ***Serverless-Webpack Version you're using***: 3.0.0-rc2
* ***Webpack version you're using***: 3.5.5
* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: Mac OS

**Comment by HyperBrain** [comment] 2017-08-25 12:45
Is this really the Serverless version you're using? Serverless Framework Version you're using: 1.7.0
This version would be quite old and does not even contain the modern hooks, so it could be that it fails. Please try to upgrade SLS to at least version 1.12.

Can you try to run the `SLS_DEBUG=* serverless deploy --verbose` and post the output?
The compile step is automatically triggered by Serverless, so there is no explicit start in the plugin itself.

Another thing that might be an issue is the loader definition in your webpack config. Since webpack 2 it should be defined differently as `module:rules`:
```
	module: {
		rules: [
			{
				// Process ES6 with Babel.
				test: /\.js$/,
				use: [
					{
						loader: "babel-loader",
						options: {
                                                   ...
						}
					}
				],
			}
		]
	}
```

We use V3 of the plugin throughout our company already and transpile nearly all code from ES6 or ES7 without problems.

**Comment by l-hendriks** [comment] 2017-08-25 12:58
Thanks for the fast answer!

So sorry, I made a very stupid typo in the sls version (1.17.0).

When I try `SLS_DEBUG=* serverless deploy --verbose` option on 3.0.0-rc.2 I get:

```
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook before:deploy:createDeploymentArtifacts
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook after:deploy:createDeploymentArtifacts
Serverless: Bundling with Webpack...

Serverless: Zip service: .../project/.webpack/service [28 ms]
Serverless: Packaging service...
Serverless: Remove .../project/.webpack
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (8.5 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
```

It seems webpack did work, but the zip file is 8.5MB instead of 77KB (which it is using serverless-webpack v2). When I unpack the zip file, I get the complete contents of the Lambda function, without the packed handler.js.

If I do the same with invoke local, I get this:

```
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook before:deploy:createDeploymentArtifacts
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook after:deploy:createDeploymentArtifacts
Serverless: Bundling with Webpack...
```

Changing the module rules doesn't help unfortunately.

Maybe something changed with how it handles the folder structure? We use it like this:

```
./services/someService/handler.js
./services/someService/package.json => has serverless-webpack, webpack, etc
./.babelrc
./.package.json => has babel-*

```

**Comment by HyperBrain** [comment] 2017-08-25 13:11
Ok. Then it can be the handler definition in your serverless.yml and your manual entry and file definition in the webpack conf. The packaging of sources points to a wrong path, handler or entry declaration somewhere.

First you should change the service to use the automatic handler detection for V3 (also works with v2):
```js
// webpack.conf.js
const nodeExternals = require('webpack-node-externals'); // eslint-disable-line
const path = require('path');
const slsw = require('serverless-webpack');

module.exports = {
    entry: slsw.lib.entries,
    target: 'node',
    output: {    // output can be omitted with V3 - this is exactly the default
        libraryTarget: 'commonjs',
        path: path.join(__dirname, '.webpack'),
        filename: '[name].js',
    },
    externals: [nodeExternals()],
    module: {
        loaders: [{
            test: /\.js$/,
            loader: 'babel-loader',
            exclude: /node_modules/,
        }],
    },
};
```

Then check if the function handler definitions in your serverless.yml point to the handlers (relatively from the service root where the yml is, in case the handlers are in some subdir).

I think one of our samples in the /example folder of this repo show that.

If that works, you even can enable package: individually in your service which is now also supported in V3. Then you can have one package.json for the service and all functions will automatically only use the needed modules and have them packaged.

**Comment by HyperBrain** [comment] 2017-08-25 13:12
BTW: The webpack compile step emits the results of the webpack compile. Where these the same for V2 and V3?

**Comment by l-hendriks** [comment] 2017-08-25 13:26
Very strange, when I update webpack config I still get the same thing. When I only change the version number of webpack-serverless and nothing else, this is the exact difference:

```
## Version 3:

➜  serverless deploy --force
Serverless: Bundling with Webpack...
Time: 1630ms
     Asset    Size  Chunks                    Chunk Names
handler.js  299 kB       0  [emitted]  [big]  handler
  [53] ./handler.js 3.69 kB {0} [built]
  [54] projectRoot/node_modules/babel-runtime/core-js/json/stringify.js 95 bytes {0} [built]
  [55] projectRoot/node_modules/core-js/library/fn/json/stringify.js 246 bytes {0} [built]
  [56] projectRoot/node_modules/babel-runtime/regenerator/index.js 49 bytes {0} [built]
  [57] projectRoot/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime-module.js 945 bytes {0} [built]
  [59] projectRoot/node_modules/babel-runtime/helpers/asyncToGenerator.js 906 bytes {0} [built]
  [60] projectRoot/node_modules/babel-runtime/core-js/promise.js 88 bytes {0} [built]
  [83] ./helpers/serialize.js 2.11 kB {0} [built]
  [84] projectRoot/node_modules/babel-runtime/core-js/object/values.js 94 bytes {0} [built]
  [89] ./helpers/deserialize.js 1.58 kB {0} [built]
  [90] projectRoot/node_modules/babel-runtime/helpers/slicedToArray.js 1.2 kB {0} [built]
  [97] ./helpers/mergeDeep.js 1.56 kB {0} [built]
  [98] projectRoot/node_modules/babel-runtime/helpers/defineProperty.js 540 bytes {0} [built]
 [110] projectRoot/node_modules/babel-runtime/helpers/typeof.js 1.07 kB {0} [built]
 [124] external "aws-sdk" 42 bytes {0} [not cacheable]
    + 110 hidden modules
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (8.42 MB)...

## Version 2:

➜ serverless deploy --force
Serverless: Bundling with Webpack...
Time: 1854ms
     Asset    Size  Chunks                    Chunk Names
handler.js  299 kB       0  [emitted]  [big]  main
  [53] ./handler.js 3.69 kB {0} [built]
  [54] projectRoot/node_modules/babel-runtime/core-js/json/stringify.js 95 bytes {0} [built]
  [55] projectRoot/node_modules/core-js/library/fn/json/stringify.js 246 bytes {0} [built]
  [56] projectRoot/node_modules/babel-runtime/regenerator/index.js 49 bytes {0} [built]
  [57] projectRoot/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime-module.js 945 bytes {0} [built]
  [59] projectRoot/node_modules/babel-runtime/helpers/asyncToGenerator.js 906 bytes {0} [built]
  [60] projectRoot/node_modules/babel-runtime/core-js/promise.js 88 bytes {0} [built]
  [83] ./helpers/serialize.js 2.11 kB {0} [built]
  [84] projectRoot/node_modules/babel-runtime/core-js/object/values.js 94 bytes {0} [built]
  [89] ./helpers/deserialize.js 1.58 kB {0} [built]
  [90] projectRoot/node_modules/babel-runtime/helpers/slicedToArray.js 1.2 kB {0} [built]
  [97] ./helpers/mergeDeep.js 1.56 kB {0} [built]
  [98] projectRoot/node_modules/babel-runtime/helpers/defineProperty.js 540 bytes {0} [built]
 [110] projectRoot/node_modules/babel-runtime/helpers/typeof.js 1.07 kB {0} [built]
 [124] external "aws-sdk" 42 bytes {0} [not cacheable]
    + 110 hidden modules
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (77.29 KB)...
```

Note in the last line the filesize of the zip file. I see no other difference.

The serverless yaml is of this form:

```
...
plugins:
  - serverless-webpack
...
functions:
  update:
    name: someName
    handler: handler.update
...
```

**Comment by l-hendriks** [comment] 2017-08-25 13:34
Maybe it's good to note that when I execute this command:

`serverless webpack --out dist`

I do get a `dist` folder with a packed handler.js

**Comment by l-hendriks** [comment] 2017-08-25 13:38
When I unpack the 8MB folder and check the contents, it is actually the whole service folder, including the `.webpack` folder with the packed `handler.js`. But the `handler.js` file in the zip root is the unpacked version.

**Comment by HyperBrain** [comment] 2017-08-25 13:42
Ok. That proves that it is dependent on your service layout and the new packaging in V3 does not handle that case correctly.
Can you set up a very simple demo project with that we can reproduce the issue? I will try to figure out what goes wrong exactly and we can see how the problem can be solved in this case. Nevertheless the demo project should use slsw.lib because that's now the recommended entry definition.

**Comment by l-hendriks** [comment] 2017-08-25 13:57
Ok thanks for the replies. I have tried to make the code as small as possible and this is how I can still recreate the issue:

.babelrc:  
```
{
    "presets": ["es2015"],
    "plugins": [
        "transform-runtime", "transform-object-rest-spread",
        "transform-async-to-generator", "transform-imports"
    ]
}
```

handler.js  
```
module.exports.update = (event, context) => { context.succeed('yay'); };
```

package.json  
```
{
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-jest": "^19.0.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-imports": "^1.4.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "serverless-webpack": "^3.0.0-rc.2",
    "webpack": "^3.5.5",
    "webpack-node-externals": "^1.6.0"
  }
}
```

serverless.yml:  
```
service: testservice

plugins:
  - serverless-webpack

functions:
  update:
    name: testservice
    handler: handler.update

provider:
  name: aws
  variableSyntax: \${((env|self|opt|file|cf|s3)[:\(][ :a-zA-Z0-9._,\-\/\(\)]*?)}
  runtime: nodejs6.10
  stage: test
  region: eu-central-1
```

webpack.config.js:  
```
const nodeExternals = require('webpack-node-externals'); // eslint-disable-line
const slsw = require('serverless-webpack');

module.exports = {
    entry: slsw.lib.entries,
    target: 'node',
    externals: [nodeExternals()],
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            use: [{ loader: 'babel-loader', options: { } }],
        }],
    },
};
```

Put those in a folder and run:

```
yarn install
serverless deploy
```

Change the webpack-serverless to version `^2.2.2` and it works, see output below (note the file size)

```
## Version 3

➜  project serverless deploy --force
Serverless: Bundling with Webpack...
Time: 397ms
     Asset     Size  Chunks             Chunk Names
handler.js  2.65 kB       0  [emitted]  handler
   [0] ./handler.js 97 bytes {0} [built]
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (5.42 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Stack update finished...
Service Information
service: testservice
stage: test
region: eu-central-1
api keys:
  None
endpoints:
  None
functions:
  update: testservice-test-update

## Version 2

➜  project serverless deploy --force
Serverless: Bundling with Webpack...
Time: 559ms
     Asset     Size  Chunks             Chunk Names
handler.js  2.65 kB       0  [emitted]  main
   [0] ./handler.js 97 bytes {0} [built]
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (1009 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
^C
➜  project yarn install
yarn install v0.23.4
warning No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.49s.
➜  project yarn install
yarn install v0.23.4
warning No license field
[1/4] 🔍  Resolving packages...
warning There appears to be trouble with your network connection. Retrying...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 37.76s.
```

**Comment by HyperBrain** [comment] 2017-08-25 14:06
Can you also point out the exact distribution of the files within the folders? or are they all flat in one directory?

**Comment by l-hendriks** [comment] 2017-08-25 14:15
Yes everything in a flat directory and then just issue the command from there.

We just noticed that first a zip file is created of 1KB (the correct one) and then after this, another very large zip file is created with the same filename, overwriting the correct zip file.

**Comment by HyperBrain** [comment] 2017-08-25 14:17
Oh. That sounds like Serverless interfering somehow (the plugin should completely disable Serverless' packaging, because only webpack is the source of truth, what to package). Good hint 👍

**Comment by l-hendriks** [comment] 2017-08-25 14:21
Yes we can confirm that when we remove all references to `packageModules.js` in `index.js` of webpack-serverless, the small zip file does not get created, but the big one still is. So probably serverless overwrites the zip file created by serverless-webpack. Almost there :)

**Comment by HyperBrain** [comment] 2017-08-25 14:23
Yes. I have to check what happens there. As it works for us (with SLS 1.19 + 1.20) it can be that it is a compatibility issue with 1.17. I will check that first - I remember that I implemented a fallback for versions <= 1.17 because they introduced a breaking change in exactly this area.
I'm pretty sure that for some reason the fallback is not working. I'll do a comparison with 1.20 and 1.17, to verify that.

**Comment by l-hendriks** [comment] 2017-08-25 14:28
Very nice, I can confirm that this was the issue. If I `yarn global upgrade serverless` to 1.20 then it works!

**Comment by HyperBrain** [comment] 2017-08-25 14:29
Ok. but the it still should be fixed. Locking Serverless to >= 1.18 is not a good solution. But thanks for all the info and help to find the reason of the issue.
Can you adapt the issue subject to reflect the Serverless version?

**Comment by l-hendriks** [comment] 2017-08-25 14:36
Thanks for the quick replies and helping finding a solution. Of course, I have updated the issue.

**Closed** 2017-08-29 22:49 UTC
Labels: bug, V3
