### ISSUE TITLE
update lambda function

### ISSUE THREAD

**Issue by barrytam20** [elastic-coders/serverless-webpack#98] opened 2017-02-09 19:47 UTC
there is a serverless command to only update a lambda function, without touching cloud formation
serverless deploy function --function myFunction

is there this sort of functionality from serverless-webpack?

**Comment by andrewoh531** [comment] 2017-02-13 11:19
This looks to be a duplicate of https://github.com/elastic-coders/serverless-webpack/issues/60

**Comment by HyperBrain** [comment] 2017-07-02 16:11
Duplicate. Will keep #107, fixed with #130.

**Closed by HyperBrain** 2017-07-02 16:11 UTC
