### ISSUE TITLE
serverless include/exclude is not processed

### ISSUE THREAD

**Issue by hereandnow** [elastic-coders/serverless-webpack#64] opened 2016-11-30 07:47 UTC
as i have seen there are/were already issues where part of this problem were discussed. 

does it make sense at all? in my special case i needed the `package.json` (and especially the `name` and `version`)-property inside AWS.

i achieved it using the existing `packExternalModules`-functionality and using the existing `package.json`-Content without all dependencies for the `tmpPackageJson`. [see commit here](https://github.com/valiton/serverless-webpack/commit/455dd224fb45c8cb5ecd85396158c8dc977d1613)

This works for my special Case (maybe it is generally i good way to do this, if you too think i can provide a pull request for this).

What would be better i think is to make the include from serverless work. If you think this would make sense, i'm willing to contribute and make a pull request for that one. just let me know in this issue!

**Comment by hereandnow** [comment] 2016-12-15 10:56
no one?

**Comment by drazafsky** [comment] 2016-12-17 21:24
I just recently ran into this issue as well. I would certainly like to see the webpack plugin including/excluding based on the values in the serverless.yml but I don't currently have the time to develop it myself.

**Comment by thenikso** [comment] 2016-12-23 17:16
the [exclude/include](https://serverless.com/framework/docs/providers/aws/guide/packaging/#exclude--include) thing looks neat and we should find a way to make it easy to use it together with webpack. I still don't have a clear idea about it. The thing is, with webpack you basically shouldn't want to include/exclude anything via serverless as the whole process should be handled by the webpack bundling process. 

however clearer docs/examples on this would definitely help in using this plugin. Opinions/suggestions are welcome!

**Comment by drazafsky** [comment] 2016-12-23 17:36
At the time I ran into this issue, I was using a setup similar to https://github.com/vitaly-t/pg-promise-demo where sql queries are being stored in external files. However, the pg-promise library doesn't require/import these and so they weren't being bundled by webpack.

After having done some more digging into webpack, I manged to get the raw-loader to add the files when bundling so my use case for this is currently solved.

**Comment by RubenSandwich** [comment] 2017-02-24 19:42
@thenikso One reason to keep exclude/include and process them only after webpack has finished in for included binaries. I have a portable binary that I ship with my lambda and I've struggling to include that whole directory with webpack.

**Comment by rstims** [comment] 2017-03-21 22:04
@RubenSandwich any chance you could post your webpack config for the binary copying?  TIA

**Comment by RubenSandwich** [comment] 2017-03-23 13:20
@rstims Sorry for the wait. I'm happy you were able to work it out. I don't have that code anymore as my team ultimately decided to move away from binaries in our lambda deployment and instead moved towards another solution because static linking all of the binaries we needed turned out to be a pain and not easily reproducible and our project requirements demand it to be easily reproducable. 

But the gist of what I did was use webpack-shell-plugin to run a shell command that did two things on the onBuildStart hook:
1. Create the .webpack directory that serverless-webpack uses as a temp directory while building
2. Copy over the binaries into the .webpack directory
I also cleaned up the webpack-shell-plugin to be less console happy: https://github.com/CMP-Studio/webpack-shell-plugin.

**Comment by alfonsoperez** [comment] 2017-06-01 04:13
Thanks so much @RubenSandwich , I was frustrated with this. In my case just by using:

``` javascript
  plugins: [
    new CopyWebpackPlugin([
      {
        from: path.join(__dirname, "binary-file")
      }
    ])
```

Solved the issue

**Comment by HyperBrain** [comment] 2017-07-31 18:58
@alfonsoperez Yes. Using the CopyWebpackPlugin is the way to go to include arbitrary files into the output package.

**Comment by HyperBrain** [comment] 2017-08-23 10:18
`3.0.0-rc.2` now also works correctly with the `file-loader` and I assume all other Webpack loaders and plugins too (even the elm-loader works without problems, see #191 ). So packaging and loading external files should not be a problem anymore. Webpack should be updated to a recent version though. Closing this issue.

**Closed by HyperBrain** 2017-08-23 10:18 UTC

**Comment by ro-savage** [comment] 2018-01-31 04:34
I am a little confused how to do this on a per function basis

if I have 
```
/folder1/function1.js
/folder1/somebinary.jpg
/folder2/function2.js
```
If I do
`  plugins: [ new CopyWebpackPlugin([{from: 'folder1/somebinary.png'}])]`

Then it will copy the file into every Lambda.

How can you make it work, so it'll only copy the file to the relavent lambda?
